// Copyright (C) 2022  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 915 10/25/2022)
// Created on Sat Mar 25 14:59:46 2023

controll_for_fft controll_for_fft_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.insignal(insignal_sig) ,	// input [13:0] insignal_sig
	.sink_valid(sink_valid_sig) ,	// output  sink_valid_sig
	.sink_sop(sink_sop_sig) ,	// output  sink_sop_sig
	.sink_eop(sink_eop_sig) ,	// output  sink_eop_sig
	.inverse(inverse_sig) ,	// output  inverse_sig
	.sink_ready(sink_ready_sig) ,	// output  sink_ready_sig
	.sink_error(sink_error_sig) ,	// output [1:0] sink_error_sig
	.outreal(outreal_sig) ,	// output [13:0] outreal_sig
	.outimag(outimag_sig) ,	// output [13:0] outimag_sig
	.fft_pts(fft_pts_sig) 	// output [10:0] fft_pts_sig
);

